### ISSUE TITLE
https://karljoke.herokuapp.com/ Application Error

### ISSUE THREAD

**Issue by EliMCGamerGuy** [eklavyadev/karljoke#7]
I was using this to get random jokes in python as the python module for jokes is subpar in my opinion. it was working at least as of 2/26/2022, but it doesn't now. When I open the URL in my browser it redirects to a heroku application error.

here's the code I was using:
```
import requests
import json

f = r"https://karljoke.herokuapp.com/jokes/random"
a = requests.get(f)
b = json.loads(a.text)

print(f"{b['setup']}\n{b['punchline']}")
```

**Comment by eklavyadev** [comment]
Thanks for informing me, there were some production errors I see, I did it now and you can use karljoke 😊
